python3 allocate_rowwise_space.py nasasrb/nasasrb.mtx &
python3 allocate_rowwise_space.py pkustk05/pkustk05.mtx &
python3 allocate_rowwise_space.py ex11/ex11.mtx &
python3 allocate_rowwise_space.py lhr71/lhr71.mtx &
python3 allocate_rowwise_space.py bbmat/bbmat.mtx &
python3 allocate_rowwise_space.py cage12/cage12.mtx &
python3 allocate_rowwise_space.py filter3D/filter3D.mtx &
python3 allocate_rowwise_space.py scircuit/scircuit.mtx &
python3 allocate_rowwise_space.py wiki-Vote/wiki-Vote.mtx &
python3 allocate_rowwise_space.py amazon0312/amazon0312.mtx &