python3 main_spmm.py nasasrb/nasasrb.mtx &
python3 main_spmm.py pkustk05/pkustk05.mtx &
python3 main_spmm.py ex11/ex11.mtx &
python3 main_spmm.py lhr71/lhr71.mtx &
python3 main_spmm.py bbmat/bbmat.mtx &
python3 main_spmm.py cage12/cage12.mtx &
python3 main_spmm.py filter3D/filter3D.mtx &
python3 main_spmm.py scircuit/scircuit.mtx &
python3 main_spmm.py wiki-Vote/wiki-Vote.mtx &
python3 main_spmm.py amazon0312/amazon0312.mtx &