python3 compare_dataflow.py nasasrb/nasasrb.mtx &
python3 compare_dataflow.py pkustk05/pkustk05.mtx &
python3 compare_dataflow.py ex11/ex11.mtx &
python3 compare_dataflow.py lhr71/lhr71.mtx &
python3 compare_dataflow.py bbmat/bbmat.mtx &
python3 compare_dataflow.py cage12/cage12.mtx &
python3 compare_dataflow.py filter3D/filter3D.mtx &
python3 compare_dataflow.py scircuit/scircuit.mtx &
python3 compare_dataflow.py wiki-Vote/wiki-Vote.mtx &
python3 compare_dataflow.py amazon0312/amazon0312.mtx &